There is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, There is experience, written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, I had to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates:

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**


In [7]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [3]:
df = pd.read_csv("C:/Users/shiml/Documents/shruti/Study/ML/Multiple Linear Regression/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

There are some NULL values in the dataset. To deal with these dataset features wise:
Assumptions:
Null values in the experience column can be considered as Zero coz maybe there was no experience or the person didn't want to disclose it.
For null values in the test_scores, we can take mean for now.

Secondly in experience column, values are in word, that has to be converted into numbers for analysis.
This can be done by word2Number library.

In [5]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [10]:
import math
test_score_median = math.floor(df['test_score(out of 10)'].mean())
test_score_median

7

In [11]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(test_score_median)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [13]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [14]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [15]:
reg.intercept_

14992.65144669314

In [16]:
reg.predict([[2,9,6]])

c:\users\shiml\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53713.86677124])

In [17]:
reg.predict([[12,10,10]])

c:\users\shiml\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([93747.79628651])